//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgeAutreFournisseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgeAutreFournisseur()
        {
            this.EveDecaissements = new HashSet<EveDecaissement>();
            this.EveReceptionEquipementsInfrastructures = new HashSet<EveReceptionEquipementsInfrastructure>();
        }
    
        public int CodeAutreFournisseur { get; set; }
        public string NomAutreFournisseur { get; set; }
        public string Localite { get; set; }
        public decimal SoldeInitialDetteFournisseur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveDecaissement> EveDecaissements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveReceptionEquipementsInfrastructure> EveReceptionEquipementsInfrastructures { get; set; }
    }
}
