//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgeFournisseursServicesFourniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgeFournisseursServicesFourniture()
        {
            this.EveAcquisitionServicesFournitures = new HashSet<EveAcquisitionServicesFourniture>();
            this.EveDecaissements = new HashSet<EveDecaissement>();
        }
    
        public int CodeFournisseurServiceFourniture { get; set; }
        public string NomFournisseurServiceFourniture { get; set; }
        public string Localite { get; set; }
        public decimal SoldeDette { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveAcquisitionServicesFourniture> EveAcquisitionServicesFournitures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveDecaissement> EveDecaissements { get; set; }
    }
}
