//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveAcquisitionServicesFourniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EveAcquisitionServicesFourniture()
        {
            this.EveDecaissements = new HashSet<EveDecaissement>();
        }
    
        public int CodeAcquisitionServiceFourniture { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Montant { get; set; }
        public int CodeServiceFourniture { get; set; }
        public int CodeFournisseurServiceFourniture { get; set; }
        public Nullable<int> CodeEmploye { get; set; }
        public Nullable<decimal> TransportServiceFourniture { get; set; }
    
        public virtual AgeEmploye AgeEmploye { get; set; }
        public virtual AgeFournisseursServicesFourniture AgeFournisseursServicesFourniture { get; set; }
        public virtual ResServicesFourniture ResServicesFourniture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveDecaissement> EveDecaissements { get; set; }
    }
}
