//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveEncaissementsVente
    {
        public int CodeEncaissement { get; set; }
        public int CodeVente { get; set; }
        public decimal MontantEncaisse { get; set; }
        public System.DateTime DateEncaissement { get; set; }
    
        public virtual EveEncaissement EveEncaissement { get; set; }
        public virtual EveVente EveVente { get; set; }
    }
}
