//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvePresenceEmploye
    {
        public int CodePresence { get; set; }
        public int CodeEmploye { get; set; }
        public int CodeUtilisationDesRessources { get; set; }
    
        public virtual AgeEmploye AgeEmploye { get; set; }
    }
}
