//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveProductionProduitsSemiFini
    {
        public int CodeProduction { get; set; }
        public int CodeProduitSemiFini { get; set; }
        public float QuantiteProduitSemiFini { get; set; }
    
        public virtual EveProduction EveProduction { get; set; }
        public virtual ResStockProduitsSemiFini ResStockProduitsSemiFini { get; set; }
    }
}
