//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveSortieDechetsMatieresPremiere
    {
        public int CodeSortieDechet { get; set; }
        public System.DateTime DateSortie { get; set; }
        public string Description { get; set; }
        public int CodeMatierePremiere { get; set; }
        public double QuantiteMatierePremiere { get; set; }
        public int CodeEmploye_responsable_stock_ { get; set; }
        public int CodeEmploye_autre_responsable_ { get; set; }
    
        public virtual AgeEmploye AgeEmploye { get; set; }
        public virtual AgeEmploye AgeEmploye1 { get; set; }
        public virtual ResStockMatieresPremiere ResStockMatieresPremiere { get; set; }
    }
}
