//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveUtilisationProduitsSemiFini
    {
        public int CodeUtilisationRessource { get; set; }
        public int CodeProduitSemiFini { get; set; }
        public int QuantiteProduitSemiFini { get; set; }
    
        public virtual EveUtilisationRessource EveUtilisationRessource { get; set; }
        public virtual ResStockProduitsSemiFini ResStockProduitsSemiFini { get; set; }
    }
}
