//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveUtilisationRessource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EveUtilisationRessource()
        {
            this.EveProductions = new HashSet<EveProduction>();
            this.EveUtilisationMatieresPremieres = new HashSet<EveUtilisationMatieresPremiere>();
            this.EveUtilisationProduitsSemiFinis = new HashSet<EveUtilisationProduitsSemiFini>();
            this.ResEquipementsInfrastructures = new HashSet<ResEquipementsInfrastructure>();
        }
    
        public int CodeEmploye_Resp_production_ { get; set; }
        public int CodeEmploye_Resp_stock_matiere_premiere_ { get; set; }
        public int CodeUtilisationRessources { get; set; }
    
        public virtual AgeEmploye AgeEmploye { get; set; }
        public virtual AgeEmploye AgeEmploye1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveProduction> EveProductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveUtilisationMatieresPremiere> EveUtilisationMatieresPremieres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveUtilisationProduitsSemiFini> EveUtilisationProduitsSemiFinis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResEquipementsInfrastructure> ResEquipementsInfrastructures { get; set; }
    }
}
