//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EveVente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EveVente()
        {
            this.EveEncaissementsVentes = new HashSet<EveEncaissementsVente>();
            this.EveVenteStockProduitsFinis = new HashSet<EveVenteStockProduitsFini>();
        }
    
        public int CodeVente { get; set; }
        public int CodeClient { get; set; }
        public int CodeEmploye { get; set; }
        public System.DateTime DateVente { get; set; }
    
        public virtual AgeClient AgeClient { get; set; }
        public virtual AgeEmploye AgeEmploye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveEncaissementsVente> EveEncaissementsVentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveVenteStockProduitsFini> EveVenteStockProduitsFinis { get; set; }
    }
}
