//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResStockProduitsFini
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResStockProduitsFini()
        {
            this.EveProductionStockProduitsFinis = new HashSet<EveProductionStockProduitsFini>();
            this.EveVenteStockProduitsFinis = new HashSet<EveVenteStockProduitsFini>();
        }
    
        public int CodeProduit { get; set; }
        public string NomProduit { get; set; }
        public int StockProduit { get; set; }
        public int PrixDeVenteStandard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveProductionStockProduitsFini> EveProductionStockProduitsFinis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveVenteStockProduitsFini> EveVenteStockProduitsFinis { get; set; }
    }
}
