//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResStockMatieresPremiere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResStockMatieresPremiere()
        {
            this.EveReceptionMatieresPremieres = new HashSet<EveReceptionMatieresPremiere>();
            this.EveUtilisationMatieresPremieres = new HashSet<EveUtilisationMatieresPremiere>();
            this.ResStockProduitsSemiFinis = new HashSet<ResStockProduitsSemiFini>();
            this.EveReceptionDonsMatieresPremieres = new HashSet<EveReceptionDonsMatieresPremiere>();
            this.EveSortieDechetsMatieresPremieres = new HashSet<EveSortieDechetsMatieresPremiere>();
            this.EveTransvasements = new HashSet<EveTransvasement>();
            this.EveTransvasements1 = new HashSet<EveTransvasement>();
        }
    
        public int CodeMatierePremiere { get; set; }
        public string NomMatiere { get; set; }
        public float StockMatiere { get; set; }
        public Nullable<decimal> CoutUnitaire { get; set; }
        public int CodeTypeMatiere { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveReceptionMatieresPremiere> EveReceptionMatieresPremieres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveUtilisationMatieresPremiere> EveUtilisationMatieresPremieres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResStockProduitsSemiFini> ResStockProduitsSemiFinis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveReceptionDonsMatieresPremiere> EveReceptionDonsMatieresPremieres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveSortieDechetsMatieresPremiere> EveSortieDechetsMatieresPremieres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveTransvasement> EveTransvasements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveTransvasement> EveTransvasements1 { get; set; }
        public virtual TypesMatiere TypesMatiere { get; set; }
    }
}
