//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResStockProduitsSemiFini
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResStockProduitsSemiFini()
        {
            this.EveProductionProduitsSemiFinis = new HashSet<EveProductionProduitsSemiFini>();
            this.EveUtilisationProduitsSemiFinis = new HashSet<EveUtilisationProduitsSemiFini>();
        }
    
        public int CodeProduitSemiFini { get; set; }
        public int CodeMatierePremiere { get; set; }
        public int Quantite { get; set; }
        public string Description { get; set; }
        public int CoutUnitaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveProductionProduitsSemiFini> EveProductionProduitsSemiFinis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveUtilisationProduitsSemiFini> EveUtilisationProduitsSemiFinis { get; set; }
        public virtual ResStockMatieresPremiere ResStockMatieresPremiere { get; set; }
        public virtual ResStockProduitsSemiFini ResStockProduitsSemiFinis1 { get; set; }
        public virtual ResStockProduitsSemiFini ResStockProduitsSemiFini1 { get; set; }
    }
}
