//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEcologieSysInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResStockMatieresPremiere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResStockMatieresPremiere()
        {
            this.EveReceptionMatieresPremieres = new HashSet<EveReceptionMatieresPremiere>();
            this.EveUtilisationMatieresPremieres = new HashSet<EveUtilisationMatieresPremiere>();
            this.ResStockProduitsSemiFinis = new HashSet<ResStockProduitsSemiFini>();
        }
    
        public int CodeMatierePremiere { get; set; }
        public string NomMatiere { get; set; }
        public float StockMatiere { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveReceptionMatieresPremiere> EveReceptionMatieresPremieres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EveUtilisationMatieresPremiere> EveUtilisationMatieresPremieres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResStockProduitsSemiFini> ResStockProduitsSemiFinis { get; set; }
    }
}
